### ISSUE TITLE
Improve the readme

### ISSUE THREAD

**Issue by annu12340** [annu12340/Choose-Smart#1]
Update the readme file with:-

Better description in the readme
Installation steps

**Comment by dahiya-code** [comment]
I am from IITBHU
Please assign it me

**Comment by tarunjain1st** [comment]
Hey @annu12340 kindly assign this to me

**Comment by Areeb786123** [comment]
i want to contribute

**Comment by aviavinashkr** [comment]
Hey, @annu12340 I would like to contribute to it. Will Kindly assign it to me for Hacktoberfest 2020
Thank You

**Comment by annu12340** [comment]
Since @navya252001 asked me first, I am assigning it to @navya252001

**Comment by dahiya-code** [comment]
I am unable to find the logo of your website

**Comment by dahiya-code** [comment]
Ma'am please help me in HACKTOBER FEST 2020
We will honor all valid pull requests prior to this change, and as of October 3, 2020 at 12:00:00 UTC – and October 3 in all time zones – pull requests will only count toward earning a T-shirt or planting a tree if they are submitted in a repository classified with the ‘hacktoberfest’ topic. The pull requests will also need to be merged, approved by a maintainer, or labeled as ‘hacktoberfest-accepted’ in order to qualify. The deadline for completions, merging, labeling, and approving is November 1.
Latest guidelines issued by the organizers
I sincerely hope you will help me
I have already made a pull request

**Comment by dahiya-code** [comment]
https://hacktoberfest.digitalocean.com/hacktoberfest-update
I am attaching the link too for your convenience

**Comment by annu12340** [comment]
> I am unable to find the logo of your website

That's because I haven't made a logo for the project 😅

**Comment by annu12340** [comment]
Solved
